### PR TITLE
Internal Website Preparation

### PR DESCRIPTION
**Pull request by marcusrelacion**

### CODE REVIEW

**Comment by marcusrelacion** [comment]
Created a new issue [Test #25](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/25) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Reduce mobile padding in accordions for legibility on mobile #26](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/26) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Double Arrow Placement #27](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/27) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Community Curated Badge #28](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/28) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [`p` shouldn't be nested within a `ul` and `l #29](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/29) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Action link's background clips off the side #30](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/30) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Submit Event Button Link #31](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/31) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [City graphic overlays on top of text #32](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/32) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Information Session Recording #33](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/33) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Reduce Spacing for Headers #34](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/34) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Reduce Text Shadow #35](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/35) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Remove Extra Periods #36](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/36) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Remove Bullet Point #39](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/39) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Accordion Arrow Rotation #40](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/40) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Add Spacing Above Bullets #41](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/41) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [A11y page content changes #42](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/42) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Decrease Header Line-height #43](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/43) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Submit Button Alignment #44](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/44) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Tablet Margin #45](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/45) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Header Text Color #46](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/46) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Section Spacing #47](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/47) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Submit Button #48](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/48) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Line-Height #49](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/49) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Badge Placement #50](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/50) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Bulleted Lists #51](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/51) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Accordion Chevron Alignment #52](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/52) in GitHub

**Pull request merged**
