### PR TITLE
Wireframes

### PR DESCRIPTION
**Pull request by marcusrelacion**

### CODE REVIEW

**Comment by joshkimux** [comment]
Created a new issue [Skip to main should have a focus style #99](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/99) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Hero Font Size #107](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/107) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Menu Font-Size #108](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/108) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Hero Line-Height #109](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/109) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Event Date Dot #110](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/110) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Section Wave Height #111](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/111) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Subscribe Fields #112](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/112) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Filter Gutter #113](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/113) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Remove In-Person & Virtual Text #114](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/114) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Events Hero #115](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/115) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Filter Styling #116](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/116) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Event Font-Color #117](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/117) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Events Spacing #118](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/118) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Events Font-Color #119](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/119) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Banner Placement #120](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/120) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Event Details Header #121](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/121) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Events Venue & Preparation #122](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/122) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Footer Styling #123](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/123) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Committee Spacing #124](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/124) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Committee Grid #125](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/125) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Filter Text #138](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/138) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Missing Waves #139](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/139) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Gutter Spacing #140](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/140) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Missing Wave #141](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/141) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Vertical Justification #142](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/142) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Add Spacing #143](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/143) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Dot Expansion #144](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/144) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Events Spacing #145](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/145) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Menu Button #146](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/146) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Speaker Font-size #147](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/147) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Footer Spacing #173](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/173) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Fitler Styles #174](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/174) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Speakers Content #175](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/175) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Add Wave #176](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/176) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Text Spacing #177](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/177) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Remove Border #178](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/178) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Add Spacing #179](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/179) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Add Spacing #185](https://github.com/AIGAdc/dcdesignweek.org-11ty/issues/185) in GitHub

**Pull request merged**
